Add build step (#8)
* Commit to open a PR

* revert env modification

* Move steps around + add os configuration

* Configure step should be working

* Move comment around

* Step build

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -41,20 +41,52 @@ on:
       out-of-tree-build:
         type: string
         required: false
+      builder-os:
+        type: string
+        required: true
+        default: '["sh-ubuntu_gcc_release"]'
+      dash-info:
+        type: string
+        required: false
+        default: 'NONE'
+        description: 'Json scructure with three parameters {"COMMIT_HASH":"fullhsashofthecommit", }'
 
 jobs:
   build:
-    runs-on: [sh-ubuntu]
+    strategy:
+      matrix:
+        os: ${{ fromJson(inputs.os) }}
+    runs-on: ${{ matrix.os }}
     steps:
+      - name: Configure builder
+        shell: bash
+        run: |
+            ## Go to workspace given by the runner (this file is generated by the pre-build script)
+            WORKSPACE=$(cat $GITHUB_WORKFLOW_SHA) 
+            echo "WORKSPACE=$WORKSPACE" >> $GITHUB_ENV
+
+            cd $WORKSPACE
+
+            ## Setup github
+            # Git config (needed by CMake ExternalProject)
+            if ! git config --get user.name; then
+                git config --system user.name 'SOFA Bot' > /dev/null 2>&1 ||
+                    git config --global user.name 'SOFA Bot' > /dev/null 2>&1 ||
+                    git config user.name 'SOFA Bot' > /dev/null 2>&1 ||
+                    echo "WARNING: cannot setup git config"
+            fi
+            if ! git config --get user.email; then
+                git config --system user.email '<>' > /dev/null 2>&1 ||
+                    git config --global user.email '<>' > /dev/null 2>&1 ||
+                    git config user.email '<>' > /dev/null 2>&1 ||
+                    echo "WARNING: cannot setup git config"
+            fi
+
+            ##TODO (if required) fix path too long for windows (see main.sh:201)
+
       - name: Clone SOFA and CI
         shell: bash
         run: |
-          ## Go to workspace given by the runner (this file is generated by the pre-build script)
-          WORKSPACE=$(cat $GITHUB_WORKFLOW_SHA) 
-          echo "WORKSPACE=$WORKSPACE" >> $GITHUB_ENV
-
-          cd $WORKSPACE
-
           ## Clone sofa and merge origin master
           echo "Cloning SOFA at commit $GITHUB_WORKFLOW_SHA"
           if [ -d  $WORKSPACE/sofa ]; then
@@ -119,7 +151,12 @@ jobs:
       - name: Notify dashboard
         shell: bash
         run: |
+          . ${CI_DIR}/scripts/utils.sh
+          . ${CI_DIR}/scripts/dashboard.sh
+
+          #Really necessary ? 
           #TODO
+          #Need more information. Might be good to
 
       - name: Build
         continue-on-error: true
@@ -127,6 +164,48 @@ jobs:
         run: |
           #TODO
           #HEre we use docker if possible
+
+          . ${CI_DIR}/scripts/utils.sh
+
+          ## Setup env variables
+          CI_PYTHON3_VERSION=${{ inputs.python-version }} # Needed by load-vm-env
+          # TODO: be able to get hostname to load correct env file --> set 
+          host_name="sofa-ci-dev-ubuntu2204-0"
+          NODE_NAME="$host_name" # Needed by load-vm-env
+          # then run 
+          load-vm-env
+
+          ## Deal with ci-depends-on
+          # Loop over each key-value pair in the JSON avoiding ci repository if inside
+          CMAKE_OPTIONS=""
+          for key in $(echo "${{ inputs.ci-depends-on }}" | jq -r 'keys[]' | grep -v '^ci$'); do
+
+            repo_url=$(echo "${{ inputs.ci-depends-on }}" | jq -r ".\"$key\".repo_url")
+            branch_name=$(echo "${{ inputs.ci-depends-on }}" | jq -r ".\"$key\".branch_name")
+
+            # Format the CMake flags for this key and append to the result
+            flag_repository="-D$(echo "$key" | gsub("\\.";"_" | ascii_upcase)_GIT_REPOSITORY=\"$repo_url\")"
+            flag_tag="-D$(echo "$key" | gsub("\\.";"_" | ascii_upcase)_GIT_TAG=\"$branch_name\")"
+
+            # Append both flags to the result string with a space
+            CMAKE_OPTIONS="$CMAKE_OPTIONS $flag_repository $flag_tag "
+          done
+
+          ## Configure the build: setup cmake variables
+          # retrive build type and compiler
+          BUILD_TYPE=$(echo ${{ matrix.os }} | awk -F '_' '{print $3}')
+          CONFIG=$(echo ${{ matrix.os }} | awk -F '_' '{print $1"_"$2}')
+
+          BUILD_OPTIONS="build-scope-${{ inputs.preset }}"
+          if [ "${{ inputs.generate-binaries }}" == "true" ]; then
+              BUILD_OPTIONS="$BUILD_OPTIONS build-release-package"
+          fi
+
+          . ${CI_DIR}/scripts/configure.sh "$BUILD_DIR" "$SRC_DIR" "$CONFIG" "$BUILD_TYPE" "$BUILD_OPTIONS" "$CMAKE_OPTIONS"
+
+          ## Call to build 
+          $SCRIPT_DIR/compile.sh "$BUILD_DIR" "$CONFIG" "$BUILD_OPTIONS"
+
 
       - name: Notify dashboard
         shell: bash
