Remove continue on fail for build + display more info on summary

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -86,6 +86,7 @@ jobs:
     runs-on: ${{ matrix.os }}
     steps:
       - name: Configure builder
+        id: configure
         shell: bash
         run: |
             ## Go to workspace given by the runner (this file is generated by the pre-build script)
@@ -119,6 +120,7 @@ jobs:
 
 
       - name: Clone SOFA and CI
+        id: clone
         shell: bash
         run: |
           cd $WORKSPACE
@@ -219,7 +221,6 @@ jobs:
 
       - name: Build
         id: build-step
-        continue-on-error: true
         shell: bash
         run: |
           ## Configure the build: setup cmake variables
@@ -318,7 +319,6 @@ jobs:
 
       - name: Launch tests
         id: launch-tests-step
-        continue-on-error: true
         if: steps.build-step.outcome == 'success' && inputs.generate-binaries == false
         shell: bash
         run: |
@@ -348,6 +348,7 @@ jobs:
       
       
       - name: Publish build logs
+        id: publish-build-logs
         if: always()
         uses: actions/upload-artifact@v4
         with:
@@ -357,6 +358,7 @@ jobs:
 
 
       - name: Publish tests logs
+        id: publish-tests-logs
         if: always()
         uses: actions/upload-artifact@v4
         with:
@@ -364,15 +366,42 @@ jobs:
           path: |
             ${{ env.BUILD_DIR }}/tests_results/
 
-      - name: Check build and test status
+      - name: Summarize results
         if: always()
         shell: bash
         run: |
-          if [[ "${{ steps.build-step.outcome }}" == "failure" ]]; then
+          bold=$(tput bold)
+          normal=$(tput sgr0)
+          if [[ "${{ steps.configure.outcome }}" == "failure" || "${{ steps.clone.outcome }}" == "failure" ]]; then
+            echo "❌ Something whent wrong during the fconfigure or clone steps..."
+            echo "${bold}Please check this action logs${normal}"
+            exit 1
+          elif [[ "${{ steps.build-step.outcome }}" == "failure" ]]; then
             echo "❌ Build step failed"
+            echo "${bold}You can download all logs here : ${{ steps.publish-build-logs.outputs.artifact-url }}${normal}"
             exit 1
           elif [[ "${{ steps.launch-tests-step.outcome }}" == "failure" ]]; then
             echo "❌ Launch tests step failed"
+            exit 1
+          elif [[ "$(cd "${{ env.BUILD_DIR }}/tests_results/" && find . -maxdepth 1 -type f)" == "" ]]; then
+            echo "❌ Tests have resulted in errors:"
+            echo ""
+            echo "#----------------------------------------#"
+            for testType in 'unit' 'scene' 'regression';
+              do 
+                for errorType in 'errors' 'crashes' 'failure';
+                do
+                  if [ -f "${{ env.BUILD_DIR }}/tests_results/${testType}-tests_${errorType}" ]; then 
+                    echo ""
+                    echo "${bold}${testType^} ${errorType}:${normal}"
+                    echo ""
+                    cat "${{ env.BUILD_DIR }}/tests_results/${testType}-tests_${errorType}"
+                    echo ""
+                    echo "#----------------------------------------#"
+                  fi
+                done
+              done
+            echo "${bold}You can download all logs here : ${{ steps.publish-tests-logs.outputs.artifact-url }}${normal}"
             exit 1
           else
             echo "✅ Both build and test steps ran successfully."
