Add better output for tests

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -377,36 +377,53 @@ jobs:
             echo "❌ Something whent wrong during the configure or clone steps..."
             echo -e "${bold}Please check those actions logs${normal}"
             exit 1
-          elif [[ "${{ steps.build-step.outcome }}" == "failure" ]]; then
+          else
+            echo "✅ Setup OK."
+          fi
+
+          if [[ "${{ steps.build-step.outcome }}" == "failure" ]]; then
             echo "❌ Build step failed"
             echo -e "${bold}You can download all logs here : ${{ steps.publish-build-logs.outputs.artifact-url }}${normal}"
             exit 1
-          elif [[ "${{ steps.launch-tests-step.outcome }}" == "failure" ]]; then
-            echo "❌ Something whent wrong during the Launch tests step"
-            echo -e "${bold}Please check this action logs, and download tests logs here: ${{ steps.publish-tests-logs.outputs.artifact-url }}${normal}"
-            exit 1
-          elif [[ "$(cd "${{ env.BUILD_DIR }}/tests_results/" && find . -maxdepth 1 -type f)" == "" ]]; then
-            echo "❌ Tests have resulted in errors:"
-            echo ""
-            echo "#----------------------------------------#"
-            for testType in 'unit' 'scene' 'regression';
-              do 
-                for errorType in 'errors' 'crashes' 'failure';
-                do
-                  if [ -f "${{ env.BUILD_DIR }}/tests_results/${testType}-tests_${errorType}" ]; then 
-                    echo ""
-                    echo -e "${bold}${testType^} ${errorType}:${normal}"
-                    echo ""
-                    cat "${{ env.BUILD_DIR }}/tests_results/${testType}-tests_${errorType}"
-                    echo ""
-                    echo "#----------------------------------------#"
-                  fi
-                done
-              done
-            echo -e "${bold}You can download all logs here : ${{ steps.publish-tests-logs.outputs.artifact-url }}${normal}"
-            exit 1
           else
-            echo "✅ Both build and test steps ran successfully."
+            echo "✅ Build OK."
+          fi
+          
+          if [[ "${{ inputs.generate-binaries }}" == "false" ]]; then
+            if [[ "${{ steps.launch-tests-step.outcome }}" == "failure" ]]; then
+              echo "❌ Something whent wrong during the Launch tests step"
+              echo -e "${bold}Please check this action logs, and download tests logs here: ${{ steps.publish-tests-logs.outputs.artifact-url }}${normal}"
+              exit 1
+            elif [[ "$(cd "${{ env.BUILD_DIR }}/tests_results/" && find . -maxdepth 1 -type f)" == "" ]]; then
+              echo "❌ Tests have resulted in : "
+              echo ""
+              python3 ${{ env.CI_DIR }}/scripts/generate-tests-table.py "${{ env.BUILD_DIR }}/tests_results/"
+              echo ""
+              echo "#----------------------------------------#"
+              echo "#---------------Quick Logs---------------#"
+              echo "#----------------------------------------#"
+              for testType in 'unit' 'scene' 'regression';
+                do 
+                  for errorType in 'errors' 'crashes' 'failure';
+                  do
+                    if [ -f "${{ env.BUILD_DIR }}/tests_results/${testType}-tests_${errorType}" ]; then 
+                      echo ""
+                      echo -e "${bold}${testType^} ${errorType}:${normal}"
+                      echo ""
+                      cat "${{ env.BUILD_DIR }}/tests_results/${testType}-tests_${errorType}"
+                      echo ""
+                      echo "#----------------------------------------#"
+                    fi
+                  done
+                done
+              echo -e "${bold}You can download all logs here : ${{ steps.publish-tests-logs.outputs.artifact-url }}${normal}"
+              exit 1
+            else
+              echo "✅ Tests where successful : "
+              echo ""
+              python3 ${{ env.CI_DIR }}/scripts/generate-tests-table.py "${{ env.BUILD_DIR }}/tests_results/"
+              echo ""
+            fi
           fi
 
 
